import {blank,dayKey,id,number,validate,schedule,record,undo} from './core.mjs';
import {openStore,transact} from './store.mjs';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={none:'尚未設定',daily:'每天',weekly:'指定星期',needed:'需要時'};
const status={taken:'已服用',skipped:'已略過',undone:'已撤銷'};
const week=['日','一','二','三','四','五','六'];
let state=blank(),tab='today',archived=false,search='',historyDay=dayKey(),historyItem='',editing=null,busy=false;
let channel;try{channel=new BroadcastChannel('supplemind-changes');channel.onmessage=async()=>{if(!editing&&tab!=='add'){state=await transact();render();}};}catch{}
function notice(message,error=false){$('#notice').textContent=message;$('#notice').classList.toggle('error',error);}
function heading(item,detail=''){return `<div class="item-heading"><div class="pill ${esc(item.color)}" aria-hidden="true">${item.form==='錠劑'?'●':'◒'}</div><div><h3>${esc(item.name)}</h3><p class="muted">${esc(item.strength||item.form)}${detail?' · '+esc(detail):''}</p></div></div>`;}
const label=i=>names[i.frequency]+(i.frequency==='weekly'?'（週'+i.days.map(d=>week[d]).join('、')+'）':'')+(['daily','weekly'].includes(i.frequency)?' · '+i.slots.map(s=>s.time).join(' / '):'');
function confirmAction(title,message){return new Promise(resolve=>{const dialog=$('#confirm');$('#confirm-title').textContent=title;$('#confirm-text').textContent=message;const finish=value=>{dialog.close();resolve(value);};$('#approve').onclick=()=>finish(true);$('#cancel').onclick=()=>finish(false);dialog.oncancel=e=>{e.preventDefault();finish(false);};dialog.showModal();});}
async function mutate(fn,message){if(busy)return;busy=true;try{state=await transact(fn);channel?.postMessage('changed');render();notice(message);}catch(e){notice(e.message,true);}finally{busy=false;}}
function alerts(){const today=dayKey();return state.items.filter(i=>!i.archived).flatMap(i=>{const a=[];if(i.expiry<today)a.push(`<p class="alert error">${esc(i.name)} · 已於 ${i.expiry} 過期，請勿服用。</p>`);else if((Date.parse(i.expiry)-Date.parse(today))/86400000<=30)a.push(`<p class="alert">${esc(i.name)} · 將於 ${i.expiry} 到期。</p>`);if(i.stock<=i.warning)a.push(`<p class="alert">${esc(i.name)} · 庫存偏低，剩餘 ${i.stock} ${esc(i.unit)}。</p>`);return a;}).join('');}
function todayView(){const entries=schedule(state),taken=entries.filter(s=>s.event?.status==='taken').length,skipped=entries.filter(s=>s.event?.status==='skipped').length;
  let out=`<p class="muted">${new Date().toLocaleDateString('zh-TW',{year:'numeric',month:'long',day:'numeric',weekday:'long'})} · 手機當地時間</p><div class="hero"><div><p class="eyebrow">YOUR DAILY MOMENT</p><h2>${entries.length&&taken+skipped===entries.length?'今天的記錄都完成了':'照顧自己，從今天開始'}</h2><p>${entries.length?'依自己的計畫，記下每一次日常。':'從加入第一項保健品開始。'}</p><span class="badges">✓ 已服用 ${taken}　↷ 已略過 ${skipped}</span></div><div class="count">${taken+skipped}<small>/ ${entries.length} 已記錄</small></div></div><div class="section-heading"><h2>今日記錄</h2><small>依時間排列</small></div>`;
  if(!entries.length)out+='<div class="empty">今天沒有排程。<br>到「新增」加入保健品，或編輯現有排程。</div>';
  let clock='';for(const s of entries){if(clock!==s.time){clock=s.time;out+=`<h3>${clock}</h3>`;}const e=s.event,i=s.item,expired=i.expiry<dayKey(),low=i.stock<s.dose;
    out+=`<article class="card">${heading(i,`${e?e.dose:s.dose} ${i.unit}`)}${i.notes?`<p class="note">${esc(i.notes)}</p>`:''}`;
    if(e)out+=`<p class="success">${status[e.status]} · ${new Date(e.at).toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit'})}</p><button data-action="undo" data-id="${e.id}">撤銷記錄</button>`;
    else out+=`${expired?'<p class="alert error">已過期，請勿服用。</p>':low?'<p class="alert">庫存不足，請先補貨。</p>':'<p class="note">請在實際服用後記錄，或選擇略過。</p>'}<div class="actions"><button class="primary" data-action="taken" data-id="${i.id}" data-slot="${s.time}" data-dose="${s.dose}" ${expired||low?'disabled':''}>✓ 已服用</button><button data-action="skipped" data-id="${i.id}" data-slot="${s.time}" data-dose="${s.dose}">略過</button></div>`;out+='</article>';
  }
  const needed=state.items.filter(i=>!i.archived&&i.frequency==='needed');if(needed.length)out+='<h2>需要時服用</h2>';
  for(const i of needed)out+=`<article class="card">${heading(i,`庫存 ${i.stock} ${i.unit}`)}<label>本次用量（${esc(i.unit)}）<input type="number" min="0.01" step="any" value="1" id="needed-${i.id}" inputmode="decimal"></label><button class="primary" data-action="needed" data-id="${i.id}">記錄本次服用</button></article>`;
  const none=state.items.filter(i=>!i.archived&&i.frequency==='none');if(none.length)out+=`<p class="alert">尚未設定排程：${none.map(i=>esc(i.name)).join('、')}。請至保健品編輯。</p>`;
  const a=alerts();if(a)out+='<h2>值得留意</h2>'+a;
  return out+'<details><summary>關於記錄與提醒</summary><p class="note">時間依目前裝置時區，不會發送背景或鎖定畫面通知。未記錄不等於略過。App 不提供服用或搭配建議。</p></details>';
}
function collection(){let out=`<div class="section-heading"><h2>我的保健品</h2><button data-tab="add">＋ 新增</button></div><label>搜尋名稱<input id="search" type="search" value="${esc(search)}" placeholder="輸入保健品名稱"></label><label><input id="archived" type="checkbox" ${archived?'checked':''}>顯示已封存</label>`;
 const items=state.items.filter(i=>i.archived===archived&&i.name.toLowerCase().includes(search.toLowerCase()));if(!items.length)out+='<div class="empty">尚無符合的保健品。</div>';
 for(const i of items)out+=`<article class="card">${heading(i,label(i))}<div class="stats"><div><small>目前庫存</small><strong>${i.stock} ${esc(i.unit)}</strong></div><div><small>提醒門檻</small><strong>${i.warning}</strong></div><div><small>到期日</small><strong>${i.expiry}</strong></div></div>${i.notes?`<p class="note">${esc(i.notes)}</p>`:''}<div class="actions">${!archived?`<button data-action="edit" data-id="${i.id}">編輯</button><button data-action="restock" data-id="${i.id}">補貨</button>`:''}<button data-action="archive" data-id="${i.id}">${archived?'恢復':'封存'}</button></div><div id="restock-${i.id}"></div></article>`;return out;
}
function formView(item){const i=item||{name:'',unit:'粒',strength:'',form:'膠囊',color:'green',frequency:'daily',slots:[{time:'08:00',dose:1}],days:[0,1,2,3,4,5,6],stock:0,warning:5,expiry:dayKey(new Date(Date.now()+365*86400000)),start:dayKey(),end:'',notes:''};
 return `<h2>${item?'編輯保健品':'加入一份新的日常'}</h2><p class="note">依保健品標示填寫，用量與時間由你決定。</p><form id="item-form" class="card"><fieldset><legend>基本資料</legend><label>名稱<input name="name" required maxlength="100" value="${esc(i.name)}" placeholder="例如：維他命 D3"></label><div class="grid"><label>類型<select name="form">${['膠囊','錠劑','粉包','液體','其他'].map(v=>`<option ${i.form===v?'selected':''}>${v}</option>`).join('')}</select></label><label>每單位含量（選填）<input name="strength" maxlength="100" value="${esc(i.strength)}" placeholder="例如：1000 IU"></label><label>識別色<select name="color">${Object.entries({green:'薄荷綠',blue:'海洋藍',purple:'薰衣草',orange:'杏桃橘'}).map(([k,v])=>`<option value="${k}" ${i.color===k?'selected':''}>${v}</option>`).join('')}</select></label><label>庫存單位<input name="unit" maxlength="20" required value="${esc(i.unit)}" ${item?'readonly':''}></label></div></fieldset><fieldset><legend>服用計畫</legend><label>頻率<select name="frequency" id="frequency">${Object.entries(names).map(([k,v])=>`<option value="${k}" ${i.frequency===k?'selected':''}>${v}</option>`).join('')}</select></label><div id="weekday-fields" ${i.frequency!=='weekly'?'hidden':''}><p>服用日</p><div class="days">${week.map((v,d)=>`<label><input type="checkbox" name="day" value="${d}" ${i.days.includes(d)?'checked':''}>${v}</label>`).join('')}</div></div><div id="slot-fields" ${!['daily','weekly'].includes(i.frequency)?'hidden':''}><label>服用時間與用量（每行一個時段）<textarea name="slots" rows="3" placeholder="08:00, 1&#10;20:00, 2">${i.slots.map(s=>s.time+', '+s.dose).join('\n')}</textarea></label><p class="note">格式：時間, 用量。例如 08:00, 1 表示早上 8 點，1 ${esc(i.unit)}。最多 8 個時段。</p></div><div class="grid"><label>開始日期<input name="start" type="date" required value="${i.start}"></label><label>結束日期（選填）<input name="end" type="date" value="${i.end||''}"></label></div><label>個人備註<textarea name="notes" maxlength="2000">${esc(i.notes)}</textarea></label></fieldset><fieldset><legend>庫存與效期</legend><div class="grid"><label>目前庫存<input name="stock" type="number" min="0" step="any" required value="${i.stock}" ${item?'readonly':''} inputmode="decimal"></label><label>低庫存提醒門檻<input name="warning" type="number" min="0" step="any" required value="${i.warning}" inputmode="decimal"></label></div><label>到期日<input name="expiry" type="date" required value="${i.expiry}"></label></fieldset>${item?'<p class="note">編輯不改動庫存；請使用補貨。修改排程不會更改已保存的歷史記錄，請勿因變更時段重複服用。不同效期請另建一項。</p>':''}<div class="actions"><button type="button" data-tab="items">取消</button><button class="primary" type="submit">${item?'儲存變更':'加入保健品'}</button></div></form>`;
}
function history(){const recent=Array.from({length:7},(_,n)=>{let d=new Date();d.setDate(d.getDate()-6+n);return {key:dayKey(d),day:d.getDate(),week:week[d.getDay()]};});const events=state.events.filter(e=>e.day===historyDay&&(!historyItem||e.itemId===historyItem)).sort((a,b)=>b.at.localeCompare(a.at));
 let out=`<h2>每一次記錄，都值得留下</h2><div class="week">${recent.map(d=>`<button data-action="day" data-day="${d.key}" class="${d.key===historyDay?'selected':''}"><small>週${d.week}</small>${d.day}</button>`).join('')}</div><div class="grid"><label>查看日期<input id="history-day" type="date" max="${dayKey()}" value="${historyDay}"></label><label>保健品<select id="history-item"><option value="">全部</option>${state.items.map(i=>`<option value="${i.id}" ${historyItem===i.id?'selected':''}>${esc(i.name)}</option>`).join('')}</select></label></div><p class="note">未記錄不代表略過。歷史保存當時名稱與用量，不依新排程倒推。</p>`;
 if(!events.length)out+='<div class="empty">這一天還沒有符合的記錄。</div>';
 for(const e of events)out+=`<article class="card"><h3>${esc(e.name)}</h3><p>${e.dose} ${esc(e.unit)} · ${status[e.status]}</p><p class="note">${e.slot==='needed'?'需要時':e.slot} · 實際記錄 ${new Date(e.at).toLocaleString('zh-TW')}</p>${e.status!=='undone'?`<button data-action="undo" data-id="${e.id}">撤銷這筆記錄</button>`:''}</article>`;return out;
}
function backup(){return `<h2>資料在你手中</h2><article class="card backup"><h3>只在這個瀏覽器保存</h3><p>目前有 <strong>${state.items.length}</strong> 項保健品、<strong>${state.events.length}</strong> 筆記錄。</p><p>資料使用手機的 IndexedDB 儲存，不上傳 GitHub 或任何雲端資料庫，也不需要帳號。</p><p class="alert">清除網站資料、私密瀏覽、換手機或系統回收儲存空間可能造成資料遺失。Safari 與加入主畫面的版本也可能使用不同儲存空間。請定期匯出備份。</p><button class="primary" data-action="export">↓ 匯出完整 JSON 備份</button><p class="note">備份包含個人紀錄，未加密。可自行保存到 Proton Drive，App 不會自動上傳。</p><hr><h3>從備份還原</h3><p>只接受本 App 匯出的 JSON。還原會取代目前裝置的所有記錄，請先匯出現有資料。</p><label>選擇備份檔<input id="import-file" type="file" accept=".json,application/json"></label><p class="note">還原前會檢查格式並再次請你確認；驗證失败不會更動資料。</p></article><article class="card"><h3>在 iPhone 使用</h3><ol><li>使用 Safari 開啟此網站。</li><li>點「分享」→「加入主畫面」。</li><li>固定使用同一個入口，定期備份。</li></ol><p class="note">網站沒有背景通知或離線載入保證。沒有 App 密碼鎖，請用 iPhone 裝置鎖保護資料。GitHub 託管公開程式，可能記錄一般連線資訊，但本 App 不傳送你的保健品資料。</p></article>`;}
function render(){document.querySelectorAll('nav button').forEach(b=>{if(b.dataset.tab===tab)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});$('#view').innerHTML=editing?formView(state.items.find(i=>i.id===editing)):tab==='today'?todayView():tab==='items'?collection():tab==='add'?formView():tab==='history'?history():backup();bind();}
function bind(){const form=$('#item-form');if(form)form.onsubmit=async e=>{e.preventDefault();const f=new FormData(form),frequency=f.get('frequency');try{const slots=['daily','weekly'].includes(frequency)?String(f.get('slots')).trim().split('\n').filter(Boolean).map(line=>{const parts=line.split(/[,，]/).map(s=>s.trim());if(parts.length!==2)throw Error('請依「08:00, 1」格式填寫每個時段。');return {time:parts[0],dose:number(parts[1],true)};}):[];const item={id:editing||id(),name:String(f.get('name')).trim(),unit:String(f.get('unit')).trim(),strength:String(f.get('strength')).trim(),notes:String(f.get('notes')).trim(),form:f.get('form'),color:f.get('color'),frequency,slots,days:f.getAll('day').map(Number),start:f.get('start'),end:f.get('end'),stock:number(f.get('stock')),warning:number(f.get('warning')),expiry:f.get('expiry'),archived:false};validate({version:1,items:[item],events:[]});const oldEdit=editing;await mutate(d=>{const old=d.items.find(i=>i.id===item.id);if(d.items.some(i=>i.id!==item.id&&i.name===item.name))throw Error('已有同名保健品。');if(oldEdit&&!old)throw Error('品項已變更。');if(old){item.stock=old.stock;item.archived=old.archived;if(item.unit!==old.unit)throw Error('不能更改庫存單位。');Object.assign(old,item);}else d.items.push(item);editing=null;tab='items';},'已儲存保健品。');}catch(e){notice(e.message,true);}};
 const freq=$('#frequency');if(freq)freq.onchange=()=>{$('#weekday-fields').hidden=freq.value!=='weekly';$('#slot-fields').hidden=!['daily','weekly'].includes(freq.value);};
 if($('#search'))$('#search').onchange=e=>{search=e.target.value;render();};if($('#archived'))$('#archived').onchange=e=>{archived=e.target.checked;render();};
 if($('#history-day'))$('#history-day').onchange=e=>{if(e.target.value){historyDay=e.target.value;render();}};if($('#history-item'))$('#history-item').onchange=e=>{historyItem=e.target.value;render();};
 if($('#import-file'))$('#import-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>20*1024*1024)throw Error('備份檔案超過 20 MB。');const data=validate(JSON.parse(await file.text()));if(await confirmAction('取代目前所有資料？',`將還原 ${data.items.length} 項保健品、${data.events.length} 筆記錄。此操作會取代現有資料，請確認已先匯出備份。`))await mutate(d=>{d.items=data.items;d.events=data.events;},'備份已成功還原。');}catch(e){notice('無法還原：'+e.message,true);}finally{e.target.value='';}};
}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||busy)return;if(b.dataset.tab){if(editing||tab==='add'){if($('#item-form')&&!await confirmAction('離開編輯？','尚未儲存的輸入不會保留。'))return;}tab=b.dataset.tab;editing=null;notice('');state=await transact();render();return;}const action=b.dataset.action,itemId=b.dataset.id;if(!action)return;
 if(['taken','skipped'].includes(action)){await mutate(d=>record(d,itemId,b.dataset.slot,action,Number(b.dataset.dose)),action==='taken'?'已記錄服用並更新庫存。':'已略過，庫存不變。');}
 if(action==='needed'){const dose=$(`#needed-${itemId}`).value;if(await confirmAction('記錄本次服用？',`將記錄 ${dose} 單位並扣除庫存。`))await mutate(d=>record(d,itemId,'needed','taken',dose),'已記錄本次服用。');}
 if(action==='undo'&&await confirmAction('撤銷這筆記錄？','若原為服用，庫存會回補；撤銷記錄仍保留在歷史中。'))await mutate(d=>undo(d,itemId),'已撤銷記錄。');
 if(action==='edit'){editing=itemId;render();}
 if(action==='archive'){const i=state.items.find(i=>i.id===itemId);if(await confirmAction(i.archived?'恢復這項保健品？':'封存這項保健品？',i.archived?'原有排程將恢復，請確認時間及用量。':'將從日常排程移除，但保留所有歷史記錄。'))await mutate(d=>{const item=d.items.find(i=>i.id===itemId);item.archived=!item.archived;},'品項狀態已更新。');}
 if(action==='restock'){$(`#restock-${itemId}`).innerHTML=`<label>增加數量<input type="number" min="0.01" step="any" id="amount-${itemId}" inputmode="decimal"></label><p class="note">限同效期批次；不同效期請另建品項。</p><button class="primary" data-action="restock-save" data-id="${itemId}">確認補貨</button>`;}
 if(action==='restock-save'){const amount=$(`#amount-${itemId}`).value;await mutate(d=>{d.items.find(i=>i.id===itemId).stock+=number(amount,true);},'庫存已增加。');}
 if(action==='day'){historyDay=b.dataset.day;render();}
 if(action==='export'){try{const fresh=await transact();const url=URL.createObjectURL(new Blob([JSON.stringify(fresh,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`SuppleMind-backup-${dayKey()}.json`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);notice('已產生備份下載，請確認檔案已保存到「檔案」App。');}catch(e){notice(e.message,true);}}
});
document.addEventListener('visibilitychange',async()=>{if(!document.hidden&&!editing&&tab!=='add'){try{state=await transact();render();}catch(e){notice(e.message,true);}}});
try{await openStore();state=await transact();render();}catch(e){notice(e.message,true);$('#view').textContent='為避免資料遺失，目前不能記錄。請使用一般 Safari 視窗並允許網站儲存，再重新整理。';document.querySelectorAll('nav button').forEach(b=>b.disabled=true);}